### ISSUE TITLE
Improve compiling

### ISSUE THREAD

**Issue by jonijuup** [XRPLF/xrpl-hooks-ide#75]
c2wasm-api: 
- [x] compiling with optimizations by default
- [x] explore if we need some compilation options set from the IDE? (Good defaults for now) 
- [x] combining compilation with linking
- [x] forbidding C++
